### ISSUE TITLE
Getting a 500 error when rejecting a request

### ISSUE THREAD

**Issue by mvanemmerik** [aws-samples/aws-iam-temporary-elevated-access-broker#24]
I'm getting a 500 error when rejecting a request. The request is rejected, the status is updated in DynamoDB and the reject email is sent, but the below FlashMessage is displayed. 

<img width="1595" alt="image" src="https://user-images.githubusercontent.com/987158/189325977-4bf487bb-f9ba-41c3-a570-2f5d86fd55df.png">

Here's the API log. 
{ 'requestId':'bb5387b6-8e99-42a7-b642-36de59bc0725', 'ip': '<removed>, 'caller':'-', 'user':'-','requestTime':'08/Sep/2022:16:40:06 +0000', 'xrayTraceId':'Root=1-631a1ae6-583ae0e6723c7be14df47737', 'wafResponseCode':'-', 'httpMethod':'GET','resourcePath':'/get_pending_requests', 'status':'500','protocol':'HTTP/1.1', 'responseLength':'16' }

Here is the log from the custom_authorizer Lambda

ERROR Invoke Error {"errorType":"TypeError","errorMessage":"Cannot read property 'split' of undefined","stack":["TypeError: Cannot read property 'split' of undefined"," at Parser.parse (/var/task/node_modules/njwt/index.js:290:28)"," at Verifier.verify (/var/task/node_modules/njwt/index.js:349:24)"," at /var/task/node_modules/@okta/jwt-verifier/lib.js:206:21"," at new Promise (<anonymous>)"," at OktaJwtVerifier.verifyAsPromise (/var/task/node_modules/@okta/jwt-verifier/lib.js:204:12)"," at OktaJwtVerifier.verifyAccessToken (/var/task/node_modules/@okta/jwt-verifier/lib.js:238:28)"," at verifyAccessToken (/var/task/index.js:88:31)"," at Runtime.exports.handler (/var/task/index.js:134:9)"," at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:73:25)"]}

**Comment by mvanemmerik** [comment]
I was able to fix this issue by updating the PendingTable.tsx file. Line 171: I changed userInfo.user to userInfo.token.
